export const dataAm = [
  {
    id: "01",
    title: "The Death Peace Of Mind",
    subTitle: "Bad Omens",
    date: "2022",
    site: "https://www.youtube.com/watch?v=ouW_RCAI0sg",
    thumbnail: "./img/AM/1.webp",
    Post: "--",
    play: "./play/AM/1.AM.mp3",
  },
  {
    id: "02",
    title: "Teardrops",
    subTitle: "Bring Me The Horizon",
    date: "2020",
    site: "https://www.youtube.com/watch?v=L5uV3gmOH9g",
    thumbnail: "./img/AM/2.webp",
    Post: "--",
    play: "./play/AM/2.AM.mp3",
  },
  {
    id: "03",
    title: "Like A Villain",
    subTitle: "Bad Omens",
    date: "2022",
    site: "https://www.youtube.com/watch?v=Aibxit_PpAg",
    thumbnail: "./img/AM/3.webp",
    Post: "--",
    play: "./play/AM/3.AM.mp3",
  },
  {
    id: "04",
    title: "n/A",
    subTitle: "Bring Me The Horizon",
    date: "2024",
    site: "https://www.youtube.com/watch?v=CGHlZglJKuE",
    thumbnail: "./img/AM/4.webp",
    Post: "--",
    play: "./play/AM/4.AM.mp3",
  },
  {
    id: "05",
    title: "Ignorance",
    subTitle: "Paramore",
    date: "2009",
    site: "https://www.youtube.com/watch?v=OH9A6tn_P6g",
    thumbnail: "./img/AM/5.webp",
    Post: "--",
    play: "./play/AM/5.AM.mp3",
  },
];
export const dataPm = [
  {
    id: "01",
    title: "I Wanna Be Yours",
    subTitle: "Arctic Monkeys",
    date: "2013",
    site: "https://www.youtube.com/watch?v=nyuo9-OjNNg",
    thumbnail: "./img/PM/1.webp",
    Post: "--",
    play: "./play/PM/1.PM.mp3",
  },
  {
    id: "02",
    title: "Alexandra",
    subTitle: "Reality Club",
    date: "2019",
    site: "https://www.youtube.com/watch?v=nxMokRj0bl8",
    thumbnail: "./img/PM/2.webp",
    play: "./play/PM/2.PM.mp3",
  },
  {
    id: "03",
    title: "Say Yes To Heaven",
    subTitle: "Lana Del Rey",
    date: "2023",
    site: "https://www.youtube.com/watch?v=MiAoetOXKcY",
    thumbnail: "./img/PM/3.webp",
    Post: "--",
    play: "./play/PM/3.PM.mp3",
  },
  {
    id: "04",
    title: "About You",
    subTitle: "The 1975",
    date: "2022",
    site: "https://www.youtube.com/watch?v=tGv7CUutzqU",
    thumbnail: "./img/PM/4.webp",
    Post: "--",
    play: "./play/PM/4.PM.mp3",
  },
  {
    id: "05",
    title: "Sweet",
    subTitle: "Cigarettes After Sex",
    date: "2017",
    site: "https://www.youtube.com/watch?v=pZ31pyTZdh0",
    thumbnail: "./img/PM/5.webp",
    Post: "--",
    play: "./play/PM/5.PM.mp3",
  },
];
